<?php


class Settings {
	public function register() : void {
		add_image_size(KNOMIC_SLIDESHOW__LARGE, KNOMIC_SLIDESHOW__LARGE_IMAGE_WIDTH, KNOMIC_SLIDESHOW__LARGE_IMAGE_WIDTH, true);
		add_image_size(KNOMIC_SLIDESHOW__THUMB, KNOMIC_SLIDESHOW__THUMB_IMAGE_WIDTH, KNOMIC_SLIDESHOW__THUMB_IMAGE_WIDTH, true);
	}
}